[info]
name = "口袋装备"
author = "雨鹜"
version = "1.0.0"

[github]
open_source = true
overview = "https://github.com/2099123771"
url = "https://github.com/2099123771/PocketGear"

[platform.windows]
arm64 = false
arm32 = false
x86_64 = false
x86 = false

[platform.android]
arm64 = true
arm32 = true
x86_64 = false
x86 = false

[introduce]
zh-cn = "让背包里的装备也能生效，翅膀除外"
zh-hant = "讓背包裡的裝備也能生效，翅膀除外"
en = "Enable gear effects from inventory (except wings)"
ja = "インベントリ内の装備効果を有効化（羽根を除く）"
ko = "인벤토리 내 장비 효과 활성화 (날개 제외)"
de = "Ausrüstungseffekte aus dem Inventar aktivieren (außer Flügel)"
fr = "Activer les effets d'équipement depuis l'inventaire (ailes exclues)"
it = "Abilita effetti equipaggiamento dall'inventario (escluse le ali)"
es = "Activar efectos de equipo desde el inventario (excepto alas)"

[[loaders]]
name = "TEFModLoader-EternalFuture゙"
supported_versions = ["2025-05-24"]

[mod]
standards = 20250517
modx = false
